### ISSUE TITLE
Use of AND operator

### ISSUE THREAD

**Issue by tonylomax** [fac25/IET-Kebbah#103]
https://github.com/fac25/IET-Kebbah/blob/47ddd53c90024d69712079bc09767c2817c9426c/components/CountdownTimer.js#L8

This is a code styling consideration so up to you all to decide. Personally I'm not a fan of using `&&` like this. It's not immediately obvious what the expected outcome is. An `if... then` might take an extra 2 lines but it's a lot clearer imo. I would reserve `&&` for explicitly checking conditions rather than using their implicit return value to render something/make something happen

**Comment by SurPun** [comment]
Thank you Tony.
