### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by modanova** [fac25/IET-Kebbah#2]
- [x] #3
- [x] #4
- [x] #5
- [x] Display introduction to training popup
- [x] Display video on introduction to training popup
   - [x] Forbit video to show options
   - [x] Update video link
- [x] Render button -> Read transcript instead -> Hides video, Shows text
- [x] Render button -> Acknowledged -> Takes you to video training page

**Comment by SurPun** [comment]
E5 | A5
