### ISSUE TITLE
Links wrapped in buttons

### ISSUE THREAD

**Issue by RhodesPeter** [fac25/IET-Kebbah#99]
A few of your links are wrapped in button elements:

<img width="390" alt="Screenshot 2022-12-02 at 13 47 34" src="https://user-images.githubusercontent.com/18164707/205307752-9ec4b204-a152-480b-8ec3-5f06ef880369.png">

This is an issue for a few reasons, one being that when using a screenreader it will announce the link as a button like this:

<img width="683" alt="Screenshot 2022-12-02 at 13 48 40" src="https://user-images.githubusercontent.com/18164707/205307914-1a5bedc7-4b27-4d20-bd62-66ff0471ad25.png">

(This is using the Mac VoiceOver which can be opened with `command + option + F5`).

Applying your button classes directly on the link should work fine, or if this is supposed to be a button then you can remove the link from inside of it.

**Comment by SurPun** [comment]
E1
